### ISSUE TITLE
State after unlocked

### ISSUE THREAD

**Issue by pablitok** [ThomasPrior/LenovoSmartClock2#10]
Hi, I'm not sure if I'm doing something wrong but after getting to the "[The device is now rooted](https://github.com/ThomasPrior/LenovoSmartClock2?tab=readme-ov-file#-the-device-is-now-rooted-)", after I reboot, the clock shows a msg while booting saying that is unlocked, but the clock is like factory resetted: no magisk, no launcher, nothing. Is this state correct? It seems like I'm doing something wrong.
Can you help me? thanks!

**Comment by ThomasPrior** [comment]
Yes, that is normal. Flashing a new boot.img and clearing the userdata partition is essentially a full reset. You need to then follow the [steps to install a launcher and magisk again](https://github.com/ThomasPrior/LenovoSmartClock2?tab=readme-ov-file#use-the-calendar-to-download-the-launcher)
