### ISSUE TITLE
Bricked after "no space left on device"

### ISSUE THREAD

**Issue by pablitok** [ThomasPrior/LenovoSmartClock2#13]
Hi, I was playing with `adb shell` and filled a partition (I don't know how). After that, I get a bootloop, algo I've lost my dump of the stock firmware. 
Is there any place to get it so I can start from scratch, or is any rooted rom that I can install with fastboot?
Thanks!

**Comment by ThomasPrior** [comment]
The issue reported is not related to the process outlined in this repository.
