### ISSUE TITLE
Hi & Question

### ISSUE THREAD

**Issue by JMillwood-92** [ThomasPrior/LenovoSmartClock2#2]
Hi,
Thanks for your guide, it's the most comprehensive one I've found!

I was hoping you might be able to suggest where I'm going wrong as my MTKClient keeps hanging at the "Reconnecting to preloader" stage. 

I've had it succeed once and progress to download the boot.img etc, but have never been successful again with that command or any of the proceeding steps. 

Best Wishes,
Josh.

**Comment by mclayton7** [comment]
@JMillwood-92 can you post your logs? I had trouble with mtkclient too, but rolling back to v1.52 and changing a couple of the flash commands fixed it for me.

**Comment by JMillwood-92** [comment]
@mclayton7 thanks for messaging back, I'm glad its not just me.
I'll roll back to v1.52 as I'm currently using v2.0 and see if their is any improvement. 

I am guessing that this is what you mean by the logs? 
----Terminal Output from first command---
> python mtk r boot,vbmeta boot.img,vbmeta.img

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.


.........Port - Device detected :)
Preloader - 	CPU:			MT8167/MT8516/MT8362()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11005000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212c00
Preloader - 	Var1:			0xcc
Preloader - Disabling Watchdog...
Preloader - HW code:			0x8167
Preloader - Target config:		0xe5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xcb00
Preloader - 	SW Ver:			0x1
Preloader - ME_ID:			3583F563117277442AFC4121827AAE1A
Preloader - SOC_ID:			0000000000000000000000000000000000000000000000000000000000000000
PLTools - Loading payload from mt8167_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /opt/mtkclient/mtkclient/payloads/mt8167_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         08A391
DAXFlash - EMMC CID:        d6010330384133393110dddb952938f5
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x1d2000000
DAXFlash - Reconnecting to preloader
///////////////HERE HANGS UNLESS I POWER CYCLE///////////////
DAXFlash - Connected to preloader
DAXFlash
DAXFlash - [LIB]: Status error: Wrong magic
DAXFlash
DAXFlash - [LIB]: Error on sending dev ctrl 262157:Unknown: -0x1
Traceback (most recent call last):
  File "/opt/mtkclient/mtk", line 695, in <module>
    mtk = Main(args).run()
  File "/opt/mtkclient/mtkclient/Library/mtk_main.py", line 514, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "/opt/mtkclient/mtkclient/Library/mtk_da_cmd.py", line 107, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "/opt/mtkclient/mtkclient/Library/mtk_daloader.py", line 193, in upload_da
    return self.da.upload_da()
  File "/opt/mtkclient/mtkclient/Library/mtk_daxflash.py", line 1137, in upload_da
    cid = self.get_chip_id()
  File "/opt/mtkclient/mtkclient/Library/mtk_daxflash.py", line 491, in get_chip_id
    cid.hw_code, cid.hw_sub_code, cid.hw_version, cid.sw_version, cid.chip_evolution = unpack(">HHHHH",
struct.error: unpack requires a buffer of 10 bytes
 

---END---

**Comment by mclayton7** [comment]
I had similar issues, and kept experimenting with different mtkclient versions/tags until I found one that worked (v1.52 in my case). You will need to change some of the commands based on the 1.52 readme here (https://github.com/bkerler/mtkclient/blob/1.52/README.md). Mainly use different flash unlock commands to unlock the bootloader.

## v1.52 
```
python mtk xflash seccfg unlock
```
## main (latest)
```
python mtk da seccfg unlock
```

**Comment by ThomasPrior** [comment]
Hello, apologies for the slow response time. This question would probably be best directed at the MTKClient project and its maintainers here: https://github.com/bkerler/mtkclient

It's been a long time since I set up my workspace for rooting these clocks, but I believe I might have used this guide to set up MTKClient: https://forum.xda-developers.com/t/guide-mtk-how-to-use-mtkclient-and-set-it-up.4509245/

The file linked in that post is not the same as the 1.52 release and seems to roughly match the files in my MTKClient directory.

**Comment by JMillwood-92** [comment]
Sorry I meant to come back to you, but went onto night shifts. 
Your guidance along with some trial and error, eventually resulted in success thanks for your guide and assistance with my question.  

Josh.
