### ISSUE TITLE
Updates and questions

### ISSUE THREAD

**Issue by BHSPitMonkey** [ThomasPrior/LenovoSmartClock2#6]
Thanks for putting this guide together! Wanted to call out a few things:

https://github.com/ThomasPrior/LenovoSmartClock2/blob/36165146a7e65784451bc8366277ba0c1b1dc0b2/README.md?plain=1#L60-L66

This no longer works as described, since mtkclient removed `setup.py` in https://github.com/bkerler/mtkclient/commit/30b53348cc4ae73b88904bc96c33edff1f05e722 back in December. I was unsuccessful getting up and running with their new instructions, so instead I just checked out the revision right before that change and it worked (https://github.com/bkerler/mtkclient/commit/a9f222320a5ac70df326d8ea853fef2e705d8f7a).

https://github.com/ThomasPrior/LenovoSmartClock2/blob/36165146a7e65784451bc8366277ba0c1b1dc0b2/README.md?plain=1#L153-L153

FWIW, I was able to root using the newer/current Magisk v27.

https://github.com/ThomasPrior/LenovoSmartClock2/blob/36165146a7e65784451bc8366277ba0c1b1dc0b2/README.md?plain=1#L224-L225

I was unable to locate any APK, including `LSPosed_1.8.6.apk`, anywhere on LSPosed's releases page. The `.zip` file, after installation through Magisk, bundles its own management UI which is meant to be launched via a persistent notification. That notification isn't accessible from the Smart Clock's UI, but it can be launched by running:

    adb shell am start-activity -a android.intent.action.MAIN -p com.android.shell -n com.android.shell/.BugreportWarningActivity -c org.lsposed.manager.LAUNCH_MANAGER

Through this I was able to enable AnyWebView and check the boxes for the different WebView implementations I installed, but unfortunately they still aren't showing up in the Developer Tools submenu and I haven't been able to figure out why yet :confused: 

https://github.com/ThomasPrior/LenovoSmartClock2/blob/36165146a7e65784451bc8366277ba0c1b1dc0b2/README.md?plain=1#L234-L235

Take my word with a grain of salt (since I haven't even gotten this part working), but I don't think `--user 0` is doing anything here. UID `0` seems to already be the one and only user on the system (per `adb shell pm list users`).

**Comment by zombielinux** [comment]
How are you accessing the Developer Tools submenu? I'm not able to get that menu to load (granted, I'm using the Lenovo Smart Clock 1)

**Comment by BHSPitMonkey** [comment]
That's described in the [Enable Developer Options](https://github.com/ThomasPrior/LenovoSmartClock2?tab=readme-ov-file#enable-developer-options) section of the README. It's the same as any other Android device; You need to have installed a launcher first in order to get into the Settings app.

**Comment by zombielinux** [comment]
Correct, I've installed kiss (https://f-droid.org/en/packages/fr.neamar.kiss/) and the app seems to launch and either immediately crash, or disappear into the background. 

I managed to get it to play nice with 

```adb shell settings put global webview_provider com.google.android.webview```


```

**Comment by ThomasPrior** [comment]
> I was unable to locate any APK, including LSPosed_1.8.6.apk, anywhere on LSPosed's releases page.

Available here: https://apkpure.com/lsposed/org.lsposed.manager

> Through this I was able to enable AnyWebView and check the boxes for the different WebView implementations I installed, but unfortunately they still aren't showing up in the Developer Tools submenu and I haven't been able to figure out why yet 

Did you reboot after enabling in AnyWebView?

As for the mtkclient setup I haven't really had any desire to re-test for each release. I'll modify the readme to point to the version I used to avoid further confusion.
