### ISSUE TITLE
Nice Work & Question

### ISSUE THREAD

**Issue by JMillwood-92** [ThomasPrior/LenovoSmartClock2#8]
Hey,
Nice tutorial, I’ve been tinkering with the Lenovo Smart Clock 2, on and off for ages now. I successfully rooted my testing one, but have never been able to satisfactorily remove the manufacturer apps whilst maintaining things like the ability to cast audio to the speaker etc. 

My original plan was to leave the crap-ware in situ, but block the speaker from the internet as without removing the crap-ware it still phones home to google repeatedly, but if I block the internet, the call to connectivitycheck fails and the clock moans about no internet access, with an irritating overlay. 

Did you ever manage to find a solution to this? 
I tried spoofing the connectivity check and everything, but never had any success. 

Best,
Josh.

**Comment by ThomasPrior** [comment]
Yes, disable the OEM packages for Google Assistant/Chromecast and it stops
complaining.
